name: Update TOCs in Content folder

on: 
  push:
    paths:
      - 'Content/**/*.md'
  pull_request:
    paths:
      - 'Content/**/*.md'
  workflow_dispatch:

jobs:
  update-toc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate TOCs
        run: |
          chmod +x generate-toc.sh
          ./generate-toc.sh Content

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Content/**/README*.md
          if git diff --cached --quiet; then
            echo "No TOC changes to commit."
            exit 0
          fi
          git commit -m "chore: auto-update TOCs in Content folder"
          git push